/**
 * Auto-generated from terminal-script.md
 * DO NOT EDIT THIS FILE DIRECTLY - Edit terminal-script.md instead
 */

import type { TerminalScript } from "../../lib/terminal-parser";

export const TERMINAL_SCRIPT: TerminalScript = {
  "config": {
    "initialCursorDelay": 1500,
    "schoolTrigger": 12,
    "joshuaTrigger": 12,
    "typeMin": 40,
    "typeMax": 80,
    "pauseBeforeOutput": 400,
    "pauseAfterOutput": 1200
  },
  "bootSequence": [
    {
      "type": "instant",
      "text": "<b>BIOS</b> v3.21 (C) 1984",
      "delayAfter": 2000
    },
    {
      "type": "instant",
      "text": "CPU: MC68020 @ 16MHz",
      "delayAfter": 1800
    },
    {
      "type": "counter",
      "prefix": "Memory Test: ",
      "target": 4096,
      "suffix": "K OK",
      "delayAfter": 1800
    },
    {
      "type": "instant",
      "text": "",
      "delayAfter": 1200
    },
    {
      "type": "dots",
      "text": "Detecting drives",
      "dotCount": 3,
      "delayAfter": 1600
    },
    {
      "type": "instant",
      "text": "hd0: 72MB CDC Wren",
      "delayAfter": 1400
    },
    {
      "type": "instant",
      "text": "fd0: 1.2MB floppy",
      "delayAfter": 1200
    },
    {
      "type": "instant",
      "text": "",
      "delayAfter": 1600
    },
    {
      "type": "instant",
      "text": "Booting from hd(0,0)...",
      "delayAfter": 3200
    },
    {
      "type": "clear"
    },
    {
      "type": "pause",
      "delayAfter": 1200
    },
    {
      "type": "instant",
      "text": "<b>UNIX System V</b> Release 3.2",
      "delayAfter": 1400
    },
    {
      "type": "instant",
      "text": "Copyright (C) 1984 AT&T",
      "delayAfter": 1200
    },
    {
      "type": "instant",
      "text": "All Rights Reserved",
      "delayAfter": 2000
    },
    {
      "type": "instant",
      "text": "",
      "delayAfter": 1000
    },
    {
      "type": "type",
      "text": "Loading kernel modules",
      "delayAfter": 1200
    },
    {
      "type": "instant",
      "text": "<b>[ok]</b> tty",
      "delayAfter": 900
    },
    {
      "type": "instant",
      "text": "<b>[ok]</b> hd",
      "delayAfter": 800
    },
    {
      "type": "instant",
      "text": "<b>[ok]</b> lp",
      "delayAfter": 750
    },
    {
      "type": "instant",
      "text": "<b>[ok]</b> inet",
      "delayAfter": 900
    },
    {
      "type": "instant",
      "text": "<b>[ok]</b> pty",
      "delayAfter": 1600
    },
    {
      "type": "instant",
      "text": "",
      "delayAfter": 1000
    },
    {
      "type": "dots",
      "text": "Starting services",
      "dotCount": 3,
      "delayAfter": 1400
    },
    {
      "type": "instant",
      "text": "syslogd        <b>[ok]</b>",
      "delayAfter": 1100
    },
    {
      "type": "instant",
      "text": "inetd          <b>[ok]</b>",
      "delayAfter": 900
    },
    {
      "type": "instant",
      "text": "cron           <b>[ok]</b>",
      "delayAfter": 1000
    },
    {
      "type": "instant",
      "text": "telnetd        <b>[ok]</b>",
      "delayAfter": 1800
    },
    {
      "type": "instant",
      "text": "uucpd          <b>[ok]</b>",
      "delayAfter": 700
    },
    {
      "type": "instant",
      "text": "ftpd           <b>[ok]</b>",
      "delayAfter": 900
    },
    {
      "type": "instant",
      "text": "",
      "delayAfter": 1200
    },
    {
      "type": "instant",
      "text": "pandora login: operator",
      "delayAfter": 1800
    },
    {
      "type": "instant",
      "text": "Password: ********",
      "delayAfter": 1400
    },
    {
      "type": "instant",
      "text": "",
      "delayAfter": 1000
    },
    {
      "type": "instant",
      "text": "Last login: Fri Jan 30 on ttyp0",
      "delayAfter": 1200
    },
    {
      "type": "instant",
      "text": "from 10.0.1.5",
      "delayAfter": 1400
    },
    {
      "type": "instant",
      "text": "",
      "delayAfter": 800
    },
    {
      "type": "instant",
      "text": "*** <u>AUTHORIZED USE ONLY</u> ***",
      "delayAfter": 1800
    },
    {
      "type": "instant",
      "text": "",
      "delayAfter": 1600
    },
    {
      "type": "clear"
    },
    {
      "type": "pause",
      "delayAfter": 1000
    }
  ],
  "schoolSequence": [
    {
      "type": "clear"
    },
    {
      "type": "pause",
      "delayAfter": 1500
    },
    {
      "type": "system",
      "text": "CRYSTAL SPRINGS HIGH SCHOOL",
      "delayAfter": 800
    },
    {
      "type": "system",
      "text": "ADMINISTRATIVE SYSTEM",
      "delayAfter": 1200
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 800
    },
    {
      "type": "inline",
      "prompt": "USER: ",
      "text": "DABNEY",
      "delayAfter": 1800
    },
    {
      "type": "inline",
      "prompt": "PASSWORD: ",
      "text": "PENCIL",
      "delayAfter": 2000
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 800
    },
    {
      "type": "system",
      "text": "LOGGED IN AS: MR. DABNEY",
      "delayAfter": 1600
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 1200
    },
    {
      "type": "system",
      "text": "1. STUDENT RECORDS",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "2. GRADE REPORTS",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "3. ATTENDANCE",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "4. LOGOUT",
      "delayAfter": 1400
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 800
    },
    {
      "type": "inline",
      "prompt": "SELECT: ",
      "text": "2",
      "delayAfter": 1800
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 1000
    },
    {
      "type": "inline",
      "prompt": "STUDENT NAME: ",
      "text": "LIGHTMAN",
      "delayAfter": 1800
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 1200
    },
    {
      "type": "system",
      "text": "LIGHTMAN, DAVID",
      "delayAfter": 1000
    },
    {
      "type": "system",
      "text": "GRADE 11  ID: 4471829",
      "delayAfter": 1400
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 800
    },
    {
      "type": "system",
      "text": "<u>SUBJECT         GRADE             </u>",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "BIOLOGY         F",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "ENGLISH         D",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "HISTORY         D",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "PHYS ED         C",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "MATHEMATICS     F",
      "delayAfter": 1800
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 1000
    },
    {
      "type": "inline",
      "prompt": "CHANGE GRADE (Y/N): ",
      "text": "Y",
      "delayAfter": 1400
    },
    {
      "type": "inline",
      "prompt": "SUBJECT: ",
      "text": "BIOLOGY",
      "delayAfter": 1600
    },
    {
      "type": "inline",
      "prompt": "NEW GRADE: ",
      "text": "A",
      "delayAfter": 1400
    },
    {
      "type": "system",
      "text": "GRADE UPDATED.",
      "delayAfter": 1800
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 1200
    },
    {
      "type": "inline",
      "prompt": "STUDENT NAME: ",
      "text": "MACK",
      "delayAfter": 1800
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 1200
    },
    {
      "type": "system",
      "text": "MACK, JENNIFER",
      "delayAfter": 1000
    },
    {
      "type": "system",
      "text": "GRADE 11  ID: 4472156",
      "delayAfter": 1400
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 800
    },
    {
      "type": "system",
      "text": "<u>SUBJECT         GRADE             </u>",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "BIOLOGY         C",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "ENGLISH         B",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "HISTORY         B",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "PHYS ED         A",
      "delayAfter": 400
    },
    {
      "type": "system",
      "text": "MATHEMATICS     F",
      "delayAfter": 1800
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 1000
    },
    {
      "type": "inline",
      "prompt": "CHANGE GRADE (Y/N): ",
      "text": "Y",
      "delayAfter": 1400
    },
    {
      "type": "inline",
      "prompt": "SUBJECT: ",
      "text": "BIOLOGY",
      "delayAfter": 1600
    },
    {
      "type": "inline",
      "prompt": "NEW GRADE: ",
      "text": "A",
      "delayAfter": 1400
    },
    {
      "type": "system",
      "text": "GRADE UPDATED.",
      "delayAfter": 1800
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 1200
    },
    {
      "type": "inline",
      "prompt": "CONTINUE (Y/N): ",
      "text": "N",
      "delayAfter": 1400
    },
    {
      "type": "system",
      "text": "",
      "delayAfter": 800
    },
    {
      "type": "system",
      "text": "LOGGING OUT...",
      "delayAfter": 1600
    },
    {
      "type": "clear"
    },
    {
      "type": "pause",
      "delayAfter": 2000
    }
  ],
  "joshuaSequence": [],
  "unixCommands": [
    {
      "prompt": "$",
      "command": "ls -la",
      "output": [
        "drwxr-xr-x  12 root",
        "-rw-r--r--   1 .profile",
        "-rw-------   1 .runcom",
        "drwx------   3 .rhost"
      ]
    },
    {
      "prompt": "$",
      "command": "ls /etc",
      "output": [
        "hosts       passwd",
        "inittab     shadow",
        "fstab       group",
        "rc2.d       motd"
      ]
    },
    {
      "prompt": "$",
      "command": "ls -l /var/adm",
      "output": [
        "-rw-r----- syslog    47K",
        "-rw-r----- sulog      8K",
        "-rw-r----- messages  12K",
        "-rw-r----- wtmp      31K"
      ]
    },
    {
      "prompt": "$",
      "command": "pwd",
      "output": [
        "/usr/operator"
      ]
    },
    {
      "prompt": "$",
      "command": "du -s /var/adm/*",
      "output": [
        "94  syslog",
        "16  sulog",
        "24  messages",
        "62  wtmp"
      ]
    },
    {
      "prompt": "$",
      "command": "find /etc -name '*.conf'",
      "output": [
        "/etc/resolv.conf",
        "/etc/ntp.conf",
        "/etc/syslog.conf",
        "/etc/uucp/Systems"
      ]
    },
    {
      "prompt": "$",
      "command": "file /bin/sh",
      "output": [
        "MC68020 executable",
        "not stripped"
      ]
    },
    {
      "prompt": "$",
      "command": "ls /dev/console",
      "output": [
        "crw--w--w- 0,0 console"
      ]
    },
    {
      "prompt": "$",
      "command": "ps -ef | head -5",
      "output": [
        "  PID TTY  TIME CMD",
        "    0 ?    0:12 sched",
        "    1 ?    0:03 /etc/init",
        "   42 ?    0:01 /etc/cron",
        "   58 co   0:00 /bin/sh"
      ]
    },
    {
      "prompt": "$",
      "command": "uptime",
      "output": [
        "up 47 days, 12:33, 2 users"
      ]
    },
    {
      "prompt": "$",
      "command": "who",
      "output": [
        "root     console  Jan 30",
        "operator ttyp0    Jan 31"
      ]
    },
    {
      "prompt": "$",
      "command": "uname -a",
      "output": [
        "UNIX pandora 3.2 2 m68k"
      ]
    },
    {
      "prompt": "$",
      "command": "hostname",
      "output": [
        "pandora"
      ]
    },
    {
      "prompt": "$",
      "command": "id",
      "output": [
        "uid=100(operator)",
        "gid=100(users)"
      ]
    },
    {
      "prompt": "$",
      "command": "date",
      "output": [
        "Fri Jan 31 22:47:03 EST"
      ]
    },
    {
      "prompt": "$",
      "command": "cal",
      "output": [
        "MARCH 1969",
        "Su Mo Tu We Th Fr Sa",
        "                   1",
        " 2  3  4  5  6  7  8",
        " 9 10 11 12 13 14 15",
        "16 17 18 19 20 <b>21</b> 22",
        "23 24 25 26 27 28 29",
        "30 31"
      ]
    },
    {
      "prompt": "$",
      "command": "netstat -r",
      "output": [
        "Destination    Gateway",
        "default        10.0.1.1",
        "10.0.1.0       pandora",
        "127.0.0.0      localhost"
      ]
    },
    {
      "prompt": "$",
      "command": "ping 10.0.1.1",
      "output": [
        "10.0.1.1 is alive"
      ]
    },
    {
      "prompt": "$",
      "command": "finger @pandora",
      "output": [
        "root     tty0  Jan 30 08:47",
        "operator ttyp0 Jan 31 22:32"
      ]
    },
    {
      "prompt": "$",
      "command": "df -k",
      "output": [
        "Filesystem  kbytes  used  avail",
        "/dev/hd0a    71680 48320  16192",
        "/dev/hd0d    51200 12480  33664"
      ]
    },
    {
      "prompt": "$",
      "command": "dmesg | tail -3",
      "output": [
        "hd0: CDC Wren IV 72MB",
        "fd0: 1.2MB floppy",
        "tty0: console ready"
      ]
    },
    {
      "prompt": "$",
      "command": "cat /etc/motd",
      "output": [
        "UNIX System V Release 3.2",
        "pandora.local",
        "Authorized users only."
      ]
    },
    {
      "prompt": "$",
      "command": "head -3 /etc/passwd",
      "output": [
        "root:x:0:0::/root:/bin/sh",
        "daemon:x:1:1::/:/bin/sh",
        "operator:x:100:100::/usr/operator"
      ]
    },
    {
      "prompt": "$",
      "command": "grep root /etc/passwd",
      "output": [
        "root:x:0:0::/root:/bin/sh"
      ]
    },
    {
      "prompt": "$",
      "command": "wc -l /etc/passwd",
      "output": [
        "42 /etc/passwd"
      ]
    },
    {
      "prompt": "$",
      "command": "tail -2 /var/adm/syslog",
      "output": [
        "Jan 31 22:30 cron[42]: CMD",
        "Jan 31 22:31 inetd: telnet"
      ]
    },
    {
      "prompt": "$",
      "command": "echo $PATH",
      "output": [
        "/bin:/usr/bin:/usr/local/bin"
      ]
    },
    {
      "prompt": "$",
      "command": "which sh",
      "output": [
        "/bin/sh"
      ]
    },
    {
      "prompt": "$",
      "command": "env | head -3",
      "output": [
        "HOME=/usr/operator",
        "TERM=vt100",
        "SHELL=/bin/sh"
      ]
    },
    {
      "prompt": "$",
      "command": "tty",
      "output": [
        "/dev/ttyp0"
      ]
    },
    {
      "prompt": "$",
      "command": "stty",
      "output": [
        "speed 9600 baud"
      ]
    },
    {
      "prompt": "$",
      "command": "history | tail -3",
      "output": [
        "  48  ls -la",
        "  49  ps -ef",
        "  50  uptime"
      ]
    }
  ]
};
