/**
 * Build script to generate terminal-data.ts from terminal-script.md
 * Run this during build to convert markdown to TypeScript module
 */

import { parseTerminalScript } from "../lib/terminal-parser";
import fs from "fs";
import path from "path";

const script = parseTerminalScript();
const outputPath = path.join(process.cwd(), "app", "components", "terminal-data.ts");

const tsContent = `/**
 * Auto-generated from terminal-script.md
 * DO NOT EDIT THIS FILE DIRECTLY - Edit terminal-script.md instead
 */

export const TERMINAL_SCRIPT = ${JSON.stringify(script, null, 2)} as const;
`;

fs.writeFileSync(outputPath, tsContent);

console.log("✓ Generated terminal-data.ts from terminal-script.md");
