import type { NextConfig } from "next";
import fs from "fs";
import path from "path";

/** Read project stats generated by the prebuild script. */
function readProjectStats(): { testCount: number; suiteCount: number } {
  const statsPath = path.join(process.cwd(), "project-stats.json");
  try {
    const raw = fs.readFileSync(statsPath, "utf-8");
    return JSON.parse(raw);
  } catch {
    return { testCount: 0, suiteCount: 0 };
  }
}

const stats = readProjectStats();

const nextConfig: NextConfig = {
  output: "export",
  images: {
    unoptimized: true,
  },
  env: {
    TUIKIT_VERSION: process.env.TUIKIT_VERSION ?? "0.1.0",
    TUIKIT_TEST_COUNT: String(stats.testCount),
    TUIKIT_SUITE_COUNT: String(stats.suiteCount),
  },
};

export default nextConfig;
